-- ==============================================================================
-- DvgCart Complete Supabase Schema: Orders, Products, Stock & Cloud Settings
-- Run this in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query -> Run)
-- ==============================================================================

-- 1. ORDERS TABLE (Stores client data, ordered items, addresses & calculations)
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  client_name text not null,
  client_phone text not null,
  client_address text,
  city text,
  pincode text,
  payment_method text default 'WhatsApp Direct',
  notes text,
  items jsonb default '[]'::jsonb,
  subtotal numeric default 0,
  discount numeric default 0,
  total numeric not null,
  status text default 'Transmitted',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS on orders
alter table public.orders enable row level security;

-- Policies for orders (allows clients to submit orders and admin to view & calculate revenue)
drop policy if exists "Allow public order creation" on public.orders;
create policy "Allow public order creation" on public.orders for insert with check (true);

drop policy if exists "Allow public order reads" on public.orders;
create policy "Allow public order reads" on public.orders for select using (true);

drop policy if exists "Allow public order updates" on public.orders;
create policy "Allow public order updates" on public.orders for update using (true);

drop policy if exists "Allow public order deletes" on public.orders;
create policy "Allow public order deletes" on public.orders for delete using (true);

-- 2. SETTINGS TABLE (Stores Announcement Banner, Hero Banner, Promo Codes, WhatsApp config, etc.)
create table if not exists public.settings (
  key text primary key,
  value text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS on settings
alter table public.settings enable row level security;

drop policy if exists "Allow public settings read" on public.settings;
create policy "Allow public settings read" on public.settings for select using (true);

drop policy if exists "Allow public settings upsert" on public.settings;
create policy "Allow public settings upsert" on public.settings for all using (true) with check (true);

-- 3. PRODUCTS TABLE (Catalog Items, Prices, and Stock Quantities)
create table if not exists public.products (
  id text primary key,
  title text not null,
  category text,
  price numeric not null,
  stock_left integer default 10,
  description text,
  image text,
  images jsonb default '[]'::jsonb,
  specs jsonb default '[]'::jsonb,
  featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Ensure stock_left column exists if table was already created earlier
do $$
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'products' and column_name = 'stock_left') then
    alter table public.products add column stock_left integer default 10;
  end if;
end $$;

-- Enable RLS on products
alter table public.products enable row level security;

drop policy if exists "Allow public products access" on public.products;
create policy "Allow public products access" on public.products for all using (true) with check (true);

-- 4. CATEGORIES TABLE
create table if not exists public.categories (
  id text primary key,
  name text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS on categories
alter table public.categories enable row level security;

drop policy if exists "Allow public categories access" on public.categories;
create policy "Allow public categories access" on public.categories for all using (true) with check (true);
